services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"   # порт для TCP соединений
      - "8123:8123"   # порт для HTTP соединений
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "123"
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: